@startuml
top to bottom direction
hide empty methods

class Supplier{
    string compName
}

class Customer{
    string firstName
    string lastName
}

class Purchase{
    Customer cust
    List<WindowOrder> orders
}

class Receipt{
    Consultant consultant
    Purchase purchase
}

class Employee{

}

class Consultant{

}

class Location{

}

class Worker{

}

class Shippment{
    Worker worker
    Purchase Purchase
}

class Window{
    List<Glass> panels
    Frame frame
}

class WindowOrder{
    Window window
    int amount
}

class Glass{
    double thickness
    double height
    double width
    List<trait> traits
}

class Frame{
    string material
    double width
    double height
}

Supplier -- Window
Purchase -- Customer
WindowOrder -- Window
WindowOrder -- Purchase
Employee --|> Consultant
Receipt -- Purchase
Consultant -- Receipt
Location -- Supplier
Worker -- Shippment
Shippment -- Purchase
Employee --|> Worker
Glass -- Window
Frame -- Window

@enduml